name: Build and Push Frontend Image to ACR

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      VITE_ADMINSERVICE_URL: ${{ secrets.VITE_ADMINSERVICE_URL }}
      VITE_DOCTORSERVICE_URL: ${{ secrets.VITE_DOCTORSERVICE_URL }}
      VITE_USERSERVICE_URL: ${{ secrets.VITE_USERSERVICE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry using Access Key
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image with environment variables
        run: |
          docker build \
            --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
            --build-arg VITE_ADMINSERVICE_URL=${{ secrets.VITE_ADMINSERVICE_URL }} \
            --build-arg VITE_DOCTORSERVICE_URL=${{ secrets.VITE_DOCTORSERVICE_URL }} \
            --build-arg VITE_USERSERVICE_URL=${{ secrets.VITE_USERSERVICE_URL }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

